name: ci test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: text
        description: Environment

env:
  random: teste


jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name:   meh  
        run: echo ${{ vars.name }}
